---

- name: Install haproxy
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - haproxy

- name: Copy config haproxy
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    mode: "0644"
  notify: Restart_Haproxy

- name: Start haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
