---


- name: Install mariadb
  hosts: sql
  remote_user: std004
  become: true

#  vars:
#    - db_host: 192.168.31.113
#    - db_name: wordpress
#    - db_user: std004
#    - db_user_password: 321654
#    - path_to_mariadb_conf: /etc/mysql/mariadb.conf.d/50-server.cnf

  vars_files:
    - vars/defaults.yml
  roles:
    - mariadb
