- name: Install Packages for wordpress / apache / php-fpm
  ansible.builtin.apt:
    pkg:
      - apache2
      - php
      - php-fpm
      - php-mbstring
      - php-bcmath
      - php-xml
      - php-mysql
      - php-common
      - php-gd
      - php-cli
      - php-curl
      - php-zip
      - php-imagick
      - php-ldap
      - php-intl

- name: Enable module for php-fpm
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy_fcgi
    - setenvif
  notify : restart_apache

- name: Enable conf for php-fpm
  command: a2enconf "{{ item }}"
  loop:
    - php8.2-fpm
  notify : restart_apache
