---

- name: Install Packages for wordpress / apache / php-fpm
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - apache2
      - php
      - php-fpm
      - php-mbstring
      - php-bcmath
      - php-xml
      - php-mysql
      - php-common
      - php-gd
      - php-cli
      - php-curl
      - php-zip
      - php-imagick
      - php-ldap
      - php-intl

- name: Enable module for php-fpm
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy_fcgi
    - setenvif
  notify : restart_apache

- name: Enable conf for php-fpm
  ansible.builtin.command: a2enconf "{{ item }}"
  loop:
    - php8.2-fpm
  notify : restart_apache

- name: Download wordpress
  ansible.builtin.get_url:
    url: "{{ wordpress_url }}"
    dest: "{{ wordpress_path }}"
    checksum: "{{ wordpress_md5 }}"
  register: r_wordpress_directory
  tags: dl_wp

- name: Unarchive Wordpress
  ansible.builtin.unarchive:
    src: "{{ r_wordpress_directory.dest }}"
    dest: "{{ web_path }}"
    remote_src: yes
    mode: 0775
    owner: "{{ web_owner }}"
    group: "{{ web_group }}"
  tags: dl_wp
